### ISSUE TITLE
Pre-generate module symbol list

### ISSUE THREAD

**Issue by char101** [lyz-code/autoimport#217] opened 2022-07-13 16:27 UTC
## Description
One of the most useful use case for auto import is when using PyQt/PySide classes. This poses several problems

1. ambiguity, the same class exists in both PyQt and PySide and also qtpy
2. performance, these modules contains a lot of symbols and thus importing it at runtime will add to the execution time

## Possible Solution
Pre-generate the symbol list in the modules. This should be manually run by the user. Since python modules can have side effect, importing any/all modules in the PYTHONPATH could be dangerous. Module priority could be defined by using configuration file in the project directory.

**Comment by lyz-code** [comment] 2022-07-14 09:46
Hi @char101 thanks for taking the time to open yet another issue :).

Right now we don't analyze all the objects of the packages of the environment, because as you say, it will make the program really slow. There has been some work in progress in this idea, you can see it in #39.

Until that is implemented, you can use [common statements](https://lyz-code.github.io/autoimport/#configuration) both at project level or as a global configuration.

Closing as a duplicate of #39.

If you feel it's not the case we can reopen it

**Closed by lyz-code** 2022-07-14 09:46 UTC
